// Code generated by ent, DO NOT EDIT.

package ent

import (
	"gin-start/ent/schema"
	"gin-start/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsActivated is the schema descriptor for isActivated field.
	userDescIsActivated := userFields[2].Descriptor()
	// user.DefaultIsActivated holds the default value on creation for the isActivated field.
	user.DefaultIsActivated = userDescIsActivated.Default.(bool)
}
